### ISSUE TITLE
[Question] Perhaps the prefix "Write" for methods of an object MarkdownWriter is superfluous?

### ISSUE THREAD

**Issue by inyutin-maxim** [JosefPihrt/DotMarkdown#11]
Perhaps the prefix "Write" for methods of an object MarkdownWriter is superfluous?

**Comment by JosefPihrt** [comment]
Frankly, I don't think that's a good idea.

Where does this idea come from if I may ask?

**Comment by inyutin-maxim** [comment]
If to look at a code in **Readme.md** you create **MarkdownWriter** object the task of which only to write, and it seems to me obvious that all its methods are engaged in the fact that they write data


```csharp
var sb = new StringBuilder();

using (MarkdownWriter writer = MarkdownWriter.Create(sb))
{
    writer.WriteHeading1("Markdown Sample");
/// ...
    writer.WriteHorizontalRule();
}
```

**Comment by JosefPihrt** [comment]
"...Writer" class with "Write..." methods is very standardized pattern that I intend to use.

**Comment by inyutin-maxim** [comment]
Ok, thanks. Also many thanks for Roslynator

**Comment by JosefPihrt** [comment]
I'm glad you like it.
