### ISSUE TITLE
Thanks and Contributing

### ISSUE THREAD

**Issue by igloo15** [JosefPihrt/DotMarkdown#12]
I have been looking for ages for a library like this thanks for actually making one! Keep up the good work and getting stuff out there for those of us who are too lazy. Do you intend to be accepting pull requests I would love to help when I can.

**Comment by JosefPihrt** [comment]
Hi,

I'm glad that you like this library.

PRs are possible. For things other than bug fixes and typos please create an issue first.

**Comment by igloo15** [comment]
Thanks and I will look to do so in the future as I look through the library. Side note how did you create your API documentation? Was that manual or automatic?

**Comment by JosefPihrt** [comment]
@igloo15 Sorry for late answer. Please see how to generate API documentation https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToGenerateDocumentation.md
